/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        poppins: ["Poppins", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        primary: {
          50: "#f4f4fb",
          100: "#eae8f7",
          200: "#d5d1f0",
          300: "#b9b3e5",
          400: "#9990da",
          500: "#675bc8",
          600: "#5d4fc4",
          700: "#4f40bf",
          800: "#41349d",
          900: "#2e256f",
          950: "#19143d",
        },
        secondary: {
          50: "#dbfaf4",
          100: "#b3f4e8",
          200: "#68e9d1",
          300: "#20dab8",
          400: "#158f78",
          500: "#08352d",
          600: "#062822",
          700: "#041b17",
          800: "#020d0b",
          900: "#010908",
          950: "#010908",
        },
        tertiary: {
          50: "#f9f9f9",
          100: "#f7f7f7",
          200: "#f0f0f0",
          300: "#ededed",
          400: "#dfdfdf",
          500: "#cbcbcb",
          600: "#868686",
          700: "#606060",
          800: "#404040",
          900: "#202020",
          950: "#0c0c0c",
        },
        error: "#c30000",
        "error-bold": "#ed2e2e",
        "error-light": "#fff2f2",
        warning: "#a9791c",
        "warning-bold": "#f4b740",
        "warning-light": "#fff8e1",
        success: "#00966d",
        "success-bold": "#00ba88",
        "success-light": "#f3fdfa",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
